language: node_js
node_js: node
env:
- NODE_ENV=test
deploy:
  provider: heroku
  api_key:
    secure: VwBa+HJkSRDAuRLY5UTApvy7/j59sDeATSgoyrtpBsdDj/E4WUulo7gYa2JnmwGKzCJLdwaUTgKXThP+rSlFg/yGjUXRcFzPFPiAgMeHu3sdbA3iuup/VSHrbWGjFFsXQf4JPyVTkFtGUKC2jmXSfFfRUzm3H1f7ZWBLTFMgHoIBA9Pc5rQTGaWWFxR7Lw+UhOpxer877pVvHk/Oi2aigQ/kp4GalTR8HXF+He99X3W2REiHpL3bQI1zEL3gIoHnCiOVw7eKgprFY4nNMYQuhuhYKYvY6Gyq5ArizjzunqcbmiJTP9pa0Fc+tXWzRucBbpC6L6/r4TozyyDiPw6zgLjQvxOJAeVMqS4FCiGSSql4rCsXGM4fln0wacfQk7faGuv1fmzSwRoN9WJagaoJXFbsuu3Su6jVmx9UwRbyxtjb4uANmwsDUxZmdwdx3LSNzdQmM8sox8NujMLpuQm3EMmx5qCflfHbyZC2cb1Cnvz/ZoeatGn9YIXgwTXwpkQanVg66NjTw4ar2TyC3BVYXq/pq/NuKHV6spbpnOPXbpL8JIABxdg7bu7RtoU4g45izf7lqKhptmUp3aRDZYHVbFqrEBvHLUAXn6uycafehVxu4rUi6pISk5RZ4SO8E/vBk5t3UWBZwuNNeH+3nV6dFRBmTQAj9tcbvAEEHVhvdG0=
  app: listful-app
  on:
    repo: cklanac/listful-app
